### PR TITLE
Don't define _GNU_SOURCE on WIN32

### PR DESCRIPTION
**Pull request by medranocalvo**

### CODE REVIEW

**Comment by medranocalvo** [comment]
Hello, any chance to merge this? It's working fine in our setup. @ecky-l could you test it in yours?

**Comment by medranocalvo** [comment]
Rebased.

Can be safely merged:

- `_WIN32` is the correct define.
- `_GNU_SOURCE` should not be blindly defined under Windows.

Thanks.

**Comment by cyanogilvie** [comment]
This issue should now be properly managed by the build system, and a much faster freelist scan used on Windows.  Would you mind testing the latest version to see if it addresses the issues in this pull request?  The code will still define _GNU_SOURCE, but only when it is needed to access the ffsll extension to glibc, and shouldn't be in play when building on Windows

**Comment by medranocalvo** [comment]
Thank you for getting back, and thank you for the improvements.  I won't be able to test it in the next two weeks, but will do so afterwards.

**Pull request closed without merging**
